(function(){
if(!window.CostwiseDesignSystem_f2dfa3){if(!document.getElementById('cw-ds-missing')){const d=document.createElement('pre');d.id='cw-ds-missing';d.style.cssText='padding:24px;font:14px/1.6 monospace;color:#C0392B';d.textContent='Costwise design-system bundle not loaded \u2014 _ds_bundle.js is missing. It is generated by the compiler; reload once it exists.';document.body.appendChild(d);}return;}
const {Logo,SidebarNav,Icon,IconButton,Avatar,Composer,Toast}=window.CostwiseDesignSystem_f2dfa3;
const {useState,useEffect}=React;
  const {EmptyState}=window.CostwiseDesignSystem_f2dfa3;

const getNav=()=>[
  {value:'today',label:'Today',icon:<Icon name="house"/>},
  {value:'ask',label:'Ask Costwise',icon:<Icon name="sparkles"/>},
  {group:'Kitchen'},
  {value:'dishes',label:'Dishes',icon:<Icon name="utensils"/>},
  {value:'ingredients',label:'Ingredients',icon:<Icon name="carrot"/>},
  {value:'invoices',label:'Invoices',icon:<Icon name="receipt-text"/>,badge:'2'},
  {group:'Your place'},
  {value:'suppliers',label:'Suppliers',icon:<Icon name="truck"/>},
  {value:'settings',label:'Settings',icon:<Icon name="settings"/>},
];

function AppShell({onSignOut}){
  const NAV=getNav();
  const [view,setView]=useState('today');
  const [toast,setToast]=useState(null);
  useEffect(()=>{lucide.createIcons&&lucide.createIcons();},[view]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(null),3600);return()=>clearTimeout(t);},[toast]);
  const go=(v)=>setView(v);
  const screens={
    today:<TodayScreen go={go} notify={setToast}/>,
    ask:<AskScreen notify={setToast}/>,
    dishes:<DishScreen go={go} notify={setToast}/>,
    invoices:<InvoicesScreen notify={setToast}/>,
  };
  const body=screens[view]||<PlaceholderScreen label={(NAV.find(n=>n.value===view)||{}).label}/>;
  return <div style={{display:'flex',height:'100%',minHeight:0,background:'var(--surface-page)'}}>
    <aside style={{width:'var(--width-sidebar)',flex:'0 0 auto',display:'flex',flexDirection:'column',gap:6,padding:'18px 12px',borderRight:'1px solid var(--border-subtle)',background:'var(--cream-50)'}}>
      <div style={{padding:'0 6px 10px'}}><Logo size={26} src="../../assets/logo-mark-transparent.png"/></div>
      <SidebarNav value={view} onChange={go} items={NAV}/>
      <div style={{flex:1}}/>
      <div style={{background:'var(--surface-accent-soft)',borderRadius:'var(--radius-card)',padding:'14px'}}>
        <div style={{font:'var(--weight-bold) var(--text-sm)/1.3 var(--font-body)',color:'var(--gold-800)'}}>You've kept €1,840 this month</div>
        <div style={{font:'var(--type-caption)',color:'var(--gold-800)',opacity:.8,marginTop:4}}>Mostly by fixing three dish prices.</div>
      </div>
      <button onClick={onSignOut} style={{display:'flex',alignItems:'center',gap:10,padding:'10px 6px',border:0,background:'none',cursor:'pointer',font:'var(--type-label)',color:'var(--text-muted)'}}><Icon name="log-out" size={18}/>Sign out</button>
    </aside>
    <main style={{flex:1,minWidth:0,display:'flex',flexDirection:'column'}}>
      <header style={{height:'var(--height-topbar)',flex:'0 0 auto',display:'flex',alignItems:'center',gap:12,padding:'0 26px',borderBottom:'1px solid var(--border-subtle)',background:'var(--surface-glass)',backdropFilter:'blur(8px)'}}>
        <div style={{display:'flex',alignItems:'center',gap:8,flex:1,maxWidth:420,height:36,padding:'0 12px',background:'var(--surface-sunken)',borderRadius:'var(--radius-pill)',color:'var(--text-muted)'}}>
          <Icon name="search" size={16}/><span style={{font:'var(--type-body)',fontSize:'var(--text-sm)'}}>Search dishes, ingredients, invoices…</span>
        </div>
        <div style={{flex:1}}/>
        <IconButton icon={<Icon name="camera"/>} label="Snap an invoice" variant="outline" onClick={()=>notifySnap(setToast)}/>
        <IconButton icon={<Icon name="bell"/>} label="Nudges"/>
        <Avatar name="Marta Ruiz" online/>
      </header>
      <div style={{flex:1,minHeight:0,overflow:'auto'}}>{body}</div>
    </main>
    {toast&&<div style={{position:'fixed',left:'50%',bottom:26,transform:'translateX(-50%)',zIndex:80}}><Toast {...toast}/></div>}
  </div>;
}
function notifySnap(setToast){setToast({tone:'good',icon:<Icon name="check" size={18}/>,title:'Got it — reading the invoice',message:'I\u2019ll flag anything that went up.'});}
function PlaceholderScreen({label}){
  return <div style={{padding:'48px 26px',maxWidth:560,margin:'0 auto'}}>
    <EmptyState icon={<Icon name="hard-hat" size={30}/>} title={(label||'This screen')+' isn\u2019t in the kit yet'} message="Nothing was supplied for this view, so it has been left blank on purpose rather than invented."/>
  </div>;
}
window.AppShell=AppShell;
})();