(function(){
if(!window.CostwiseDesignSystem_f2dfa3){if(!document.getElementById('cw-ds-missing')){const d=document.createElement('pre');d.id='cw-ds-missing';d.style.cssText='padding:24px;font:14px/1.6 monospace;color:#C0392B';d.textContent='Costwise design-system bundle not loaded \u2014 _ds_bundle.js is missing. It is generated by the compiler; reload once it exists.';document.body.appendChild(d);}return;}
const {ChatBubble,Avatar,Composer,SuggestionChip,IconButton,Icon,Card,ProgressMeter,DataRow,Badge,Button,Dialog}=window.CostwiseDesignSystem_f2dfa3;
const {useState,useEffect,useRef}=React;
const MARK='../../assets/logo-mark-transparent.png';

function AskScreen({notify}){
  const [q,setQ]=useState('');
  const [turns,setTurns]=useState([
    {from:'agent',meta:'Today, 8:04',text:<>Morning. Your <strong>carbonara</strong> costs €3.90 a plate this week — 40c more than last, because Metro put eggs up 14%.</>,
     attach:'meter'},
    {from:'me',text:'Do I need to change the price?'},
    {from:'agent',tone:'note',text:<>Only if you want to keep the same margin. At <strong>€15.50</strong> you're back to 68% — that's 50c more than today, and still under what the two places on your street charge.</>,attach:'compare'},
  ]);
  const [thinking,setThinking]=useState(false);
  const [confirm,setConfirm]=useState(false);
  const end=useRef(null);
  useEffect(()=>{lucide.createIcons&&lucide.createIcons();},[turns,thinking,confirm]);

  const ask=(text)=>{
    setTurns(t=>[...t,{from:'me',text}]);
    setThinking(true);
    setTimeout(()=>{setThinking(false);setTurns(t=>[...t,{from:'agent',meta:'Just now',text:<>Push the <strong>sea bass</strong>. It's your widest margin at 28% food cost, and you have 4kg landing tomorrow that won't keep past Friday.</>,attach:'rows'}]);},1200);
  };

  const attachments={
    meter:<Card padding="tight" style={{minWidth:320}}>
      <ProgressMeter label="Carbonara plate cost" value={3.9} max={6} target={4.2} tone="watch" display="€3.90 of €4.20"/>
      <div style={{display:'flex',gap:8,marginTop:12,flexWrap:'wrap'}}>
        <Badge tone="watch">Eggs +14%</Badge><Badge tone="neutral">Guanciale flat</Badge><Badge tone="neutral">Pecorino flat</Badge>
      </div></Card>,
    compare:<Card padding="tight" style={{minWidth:320}}>
      <DataRow title="Keep €15.00" subtitle="Margin drops to 65%" amount="€11.10" amountNote="you keep"/>
      <DataRow title="Move to €15.50" subtitle="Back to your usual 68%" amount="€11.60" amountNote="you keep" end={<Badge tone="good">Suggested</Badge>}/>
      <div style={{display:'flex',gap:10,paddingTop:12}}>
        <Button size="sm" onClick={()=>setConfirm(true)}>Update the menu price</Button>
        <Button size="sm" variant="ghost">Leave it</Button>
      </div></Card>,
    rows:<Card padding="tight" style={{minWidth:320}}>
      <DataRow thumb={<Icon name="fish"/>} title="Grilled sea bass" subtitle="4kg arriving tomorrow" amount="28%" amountNote="food cost" end={<Badge tone="good">Push</Badge>}/>
      <DataRow thumb={<Icon name="salad"/>} title="Tomato & burrata" subtitle="Burrata up 9%" amount="32%" amountNote="food cost" end={<Badge tone="over">Hold</Badge>}/>
    </Card>,
  };

  return <div style={{display:'flex',flexDirection:'column',height:'100%',minHeight:0}}>
    <div style={{flex:1,minHeight:0,overflow:'auto',padding:'26px 26px 8px'}}>
      <div style={{maxWidth:760,margin:'0 auto',display:'flex',flexDirection:'column',gap:16}}>
        <div style={{display:'flex',alignItems:'center',gap:12,paddingBottom:6}}>
          <Avatar agent src={MARK} size="lg"/>
          <div><div style={{font:'var(--type-heading)',color:'var(--text-strong)'}}>Costwise</div>
            <div style={{font:'var(--type-caption)',color:'var(--text-muted)'}}>Knows your last 14 weeks of invoices · Casa Ruiz</div></div>
        </div>
        {turns.map((t,i)=><ChatBubble key={i} from={t.from} tone={t.tone} meta={t.meta}
          avatar={t.from==='agent'?<Avatar agent src={MARK}/>:null}
          attachment={t.attach?attachments[t.attach]:null}>{t.text}</ChatBubble>)}
        {thinking&&<ChatBubble typing avatar={<Avatar agent src={MARK}/>}/>}
        <div ref={end}/>
      </div>
    </div>
    <div style={{flex:'0 0 auto',padding:'12px 26px 22px',background:'linear-gradient(to top,var(--surface-page) 70%,rgba(253,251,246,0))'}}>
      <div style={{maxWidth:760,margin:'0 auto'}}>
        <div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:12}}>
          <SuggestionChip onClick={()=>ask('What should I push tonight?')}>What should I push tonight?</SuggestionChip>
          <SuggestionChip variant="accent" onClick={()=>ask('Which supplier got dearer?')}>Which supplier got dearer?</SuggestionChip>
          <SuggestionChip onClick={()=>ask('How was last month?')}>How was last month?</SuggestionChip>
        </div>
        <Composer value={q} onChange={e=>setQ(e.target.value)} onSend={()=>{if(q.trim()){ask(q.trim());setQ('');}}}
          lead={<Icon name="sparkles" size={16}/>} sendIcon={<Icon name="arrow-up" size={18}/>}
          tools={<><IconButton size="sm" round icon={<Icon name="camera" size={18}/>} label="Snap an invoice"/><IconButton size="sm" round icon={<Icon name="mic" size={18}/>} label="Speak"/></>}/>
      </div>
    </div>
    <Dialog open={confirm} title="Raise the carbonara to €15.50?" onClose={()=>setConfirm(false)}
      footer={<><Button variant="secondary" onClick={()=>setConfirm(false)}>Not yet</Button>
        <Button onClick={()=>{setConfirm(false);notify({tone:'good',icon:<Icon name="check" size={18}/>,title:'Menu price updated',message:'Carbonara is €15.50 from tonight.',actionLabel:'Undo'});}}>Update the menu</Button></>}>
      That keeps you at a 68% margin even if eggs stay where they are. I'll let you know if they come back down.
    </Dialog>
  </div>;
}
window.AskScreen=AskScreen;
})();