(function(){
if(!window.CostwiseDesignSystem_f2dfa3){if(!document.getElementById('cw-ds-missing')){const d=document.createElement('pre');d.id='cw-ds-missing';d.style.cssText='padding:24px;font:14px/1.6 monospace;color:#C0392B';d.textContent='Costwise design-system bundle not loaded \u2014 _ds_bundle.js is missing. It is generated by the compiler; reload once it exists.';document.body.appendChild(d);}return;}
const {Card,Badge,Button,IconButton,Icon,DataRow,ProgressMeter,StatTile,MoneyInput,Tabs,Tooltip,SuggestionChip}=window.CostwiseDesignSystem_f2dfa3;
const {useState,useEffect}=React;
const ING=[
  {n:'Guanciale',s:'Bidfood · 14 Aug',q:'60 g',c:'€1.44',up:false,i:'beef'},
  {n:'Free-range eggs',s:'Metro · price up 14%',q:'2 yolks',c:'€0.72',up:true,i:'egg'},
  {n:'Pecorino romano',s:'Metro · 11 Aug',q:'30 g',c:'€0.81',up:false,i:'milk'},
  {n:'Spaghetti',s:'Dry store',q:'110 g',c:'€0.28',up:false,i:'wheat'},
  {n:'Black pepper, oil, salt',s:'Store cupboard',q:'—',c:'€0.65',up:false,i:'utensils'},
];
function DishScreen({go,notify}){
  const [tab,setTab]=useState('Ingredients');
  const [price,setPrice]=useState('15.00');
  useEffect(()=>{lucide.createIcons&&lucide.createIcons();},[tab]);
  return <div style={{maxWidth:1000,margin:'0 auto',padding:'26px 26px 60px',display:'flex',flexDirection:'column',gap:20}}>
    <div style={{display:'flex',alignItems:'center',gap:12,flexWrap:'wrap'}}>
      <IconButton variant="outline" icon={<Icon name="arrow-left"/>} label="Back to dishes" onClick={()=>go('today')}/>
      <div style={{flex:1,minWidth:240}}>
        <div className="cw-overline">Dish</div>
        <h1 style={{font:'var(--type-title)',color:'var(--text-strong)',marginTop:2}}>Carbonara</h1>
      </div>
      <Badge tone="watch" size="lg" dot>Cost up 40c this week</Badge>
      <Button variant="secondary" iconLeft={<Icon name="pencil" size={18}/>}>Edit recipe</Button>
    </div>

    <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:'var(--gap-cards)'}}>
      <StatTile label="Plate cost" value="€3.90" delta="↑ €0.40" deltaTone="over" caption="vs last week"/>
      <StatTile label="Menu price" value={'€'+price}/>
      <StatTile label="Food cost" value="26" unit="%" delta="↑ 2.6 pts" deltaTone="over" caption="target 25%"/>
      <StatTile variant="brand" label="You keep" value="€11.10" unit="/ plate"/>
    </div>

    <div style={{display:'grid',gridTemplateColumns:'1.4fr 1fr',gap:'var(--gap-cards)',alignItems:'start'}}>
      <Card padding="tight">
        <div style={{padding:'2px 2px 12px'}}><Tabs variant="underline" value={tab} onChange={setTab} items={['Ingredients','History','Notes']}/></div>
        {tab==='Ingredients'&&<>
          {ING.map(r=><DataRow key={r.n} thumb={<Icon name={r.i}/>} title={r.n} subtitle={r.s} amount={r.c} amountNote={r.q} end={r.up?<Badge tone="over">+14%</Badge>:null}/>)}
          <div style={{display:'flex',alignItems:'center',gap:10,paddingTop:14}}>
            <Button size="sm" variant="ghost" iconLeft={<Icon name="plus" size={18}/>}>Add ingredient</Button>
            <div style={{flex:1}}/>
            <span style={{font:'var(--type-label)',color:'var(--text-muted)'}}>Plate cost</span>
            <span className="cw-money" style={{fontSize:'var(--text-md)',color:'var(--text-strong)'}}>€3.90</span>
          </div></>}
        {tab==='History'&&<div style={{padding:'6px 2px 10px',display:'flex',flexDirection:'column',gap:14}}>
          {[['Week 30','€3.42',57],['Week 31','€3.48',58],['Week 32','€3.50',58],['Week 33','€3.90',65]].map(([w,c,v])=>
            <ProgressMeter key={w} label={w} display={c} value={v} max={100} tone={v>62?'watch':'good'}/>)}
        </div>}
        {tab==='Notes'&&<p style={{font:'var(--type-body)',color:'var(--text-muted)',padding:'8px 2px 12px'}}>Nothing written down for this dish yet.</p>}
      </Card>

      <div style={{display:'flex',flexDirection:'column',gap:'var(--gap-cards)'}}>
        <Card variant="accent" eyebrow="Costwise suggests" title="€15.50 keeps your margin">
          <p style={{font:'var(--type-body)',color:'var(--ink-800)'}}>50c more than now. Still the cheapest carbonara on your street.</p>
          <div style={{marginTop:14,display:'flex',flexDirection:'column',gap:12}}>
            <MoneyInput label="Menu price" size="lg" value={price} onChange={e=>setPrice(e.target.value)}/>
            <div style={{display:'flex',gap:10,flexWrap:'wrap'}}>
              <Button size="sm" onClick={()=>{setPrice('15.50');notify({tone:'good',icon:<Icon name="check" size={18}/>,title:'Menu price updated',message:'Carbonara is €15.50 from tonight.',actionLabel:'Undo'});}}>Use €15.50</Button>
              <Button size="sm" variant="ghost">Keep €15.00</Button>
            </div>
          </div>
        </Card>
        <Card padding="tight" title="What's in the plate cost" icon={<Tooltip wrap label="What you pay for the food on one plate, before staff and rent."><Icon name="circle-help" size={16}/></Tooltip>}>
          <ProgressMeter thick segments={[{value:37},{value:21},{value:18},{value:7},{value:17}]} max={100} caption="Guanciale · Pecorino · Eggs · Pasta · Cupboard"/>
          <div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:14}}>
            <SuggestionChip variant="filter">Swap the guanciale</SuggestionChip>
            <SuggestionChip variant="filter">Compare suppliers</SuggestionChip>
          </div>
        </Card>
      </div>
    </div>
  </div>;
}
window.DishScreen=DishScreen;
})();