(function(){
if(!window.CostwiseDesignSystem_f2dfa3){if(!document.getElementById('cw-ds-missing')){const d=document.createElement('pre');d.id='cw-ds-missing';d.style.cssText='padding:24px;font:14px/1.6 monospace;color:#C0392B';d.textContent='Costwise design-system bundle not loaded \u2014 _ds_bundle.js is missing. It is generated by the compiler; reload once it exists.';document.body.appendChild(d);}return;}
const {Card,Badge,Button,IconButton,Icon,DataRow,Tabs,SuggestionChip,EmptyState,Checkbox,Select,StatTile}=window.CostwiseDesignSystem_f2dfa3;
const {useState,useEffect}=React;
const INV=[
  {id:1,who:'Metro',date:'18 Aug',items:'14 items · 3 prices changed',amt:'€412.60',tone:'watch',label:'Check'},
  {id:2,who:'Local market',date:'17 Aug',items:'Photo, not read yet',amt:'€96.20',tone:'info',label:'New'},
  {id:3,who:'Bidfood',date:'14 Aug',items:'22 items · all as expected',amt:'€688.40',tone:'good',label:'Filed'},
  {id:4,who:'Metro',date:'11 Aug',items:'9 items · all as expected',amt:'€204.15',tone:'good',label:'Filed'},
];
function InvoicesScreen({notify}){
  const [tab,setTab]=useState('todo');
  const [open,setOpen]=useState(INV[0]);
  useEffect(()=>{lucide.createIcons&&lucide.createIcons();},[tab,open]);
  const list=tab==='todo'?INV.filter(i=>i.tone!=='good'):INV;
  return <div style={{maxWidth:1060,margin:'0 auto',padding:'26px 26px 60px',display:'flex',flexDirection:'column',gap:18}}>
    <div style={{display:'flex',alignItems:'flex-end',gap:14,flexWrap:'wrap'}}>
      <div style={{flex:1,minWidth:260}}>
        <h1 style={{font:'var(--type-title)',color:'var(--text-strong)'}}>Invoices</h1>
        <p style={{font:'var(--type-body)',color:'var(--text-muted)',marginTop:6}}>Snap them, I'll read them and tell you what moved.</p>
      </div>
      <Tabs value={tab} onChange={setTab} items={[{value:'todo',label:'Needs you',count:2},{value:'all',label:'Everything'}]}/>
      <Button iconLeft={<Icon name="camera" size={18}/>} onClick={()=>notify({tone:'good',icon:<Icon name="check" size={18}/>,title:'Got it — reading the invoice',message:'I\u2019ll flag anything that went up.'})}>Snap an invoice</Button>
    </div>

    <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:'var(--gap-cards)'}}>
      <StatTile label="Spent this month" value="€4,120" delta="↑ €260" deltaTone="over" caption="vs July"/>
      <StatTile label="Prices that moved" value="7" unit="items" delta="5 up · 2 down" deltaTone="flat"/>
      <StatTile label="Invoices waiting" value="2"/>
    </div>

    <div style={{display:'grid',gridTemplateColumns:'1fr 1.15fr',gap:'var(--gap-cards)',alignItems:'start'}}>
      <Card padding="tight">
        {list.map(i=><DataRow key={i.id} thumb={<Icon name="receipt-text"/>} title={i.who+' · '+i.date} subtitle={i.items} amount={i.amt}
          end={<Badge tone={i.tone}>{i.label}</Badge>} onClick={()=>setOpen(i)}/>)}
        {!list.length&&<EmptyState compact icon={<Icon name="check" size={28}/>} title="All caught up" message="Nothing waiting on you."/>}
      </Card>

      <Card eyebrow={'Invoice · '+open.who} title={open.who+' · '+open.date} action={<IconButton icon={<Icon name="ellipsis"/>} label="More"/>}>
        <div style={{display:'flex',gap:10,flexWrap:'wrap',marginBottom:16}}>
          <Badge tone="watch" dot>3 prices changed</Badge><Badge tone="neutral">{open.amt}</Badge><Badge tone="outline">Read by Costwise</Badge>
        </div>
        <div style={{display:'flex',flexDirection:'column',gap:2}}>
          <DataRow thumb={<Icon name="egg"/>} title="Free-range eggs, 30s" subtitle="was €3.68 · now €4.20" amount="+14%" end={<Badge tone="over">Up</Badge>}/>
          <DataRow thumb={<Icon name="milk"/>} title="Cream 35%, 1L" subtitle="was €2.45 · now €2.65" amount="+8%" end={<Badge tone="over">Up</Badge>}/>
          <DataRow thumb={<Icon name="carrot"/>} title="Carrots, 10kg" subtitle="was €12.40 · now €11.00" amount="−11%" end={<Badge tone="good">Down</Badge>}/>
          <DataRow thumb={<Icon name="wheat"/>} title="11 other items" subtitle="No change" amount="€318.75"/>
        </div>
        <div style={{marginTop:16,paddingTop:16,borderTop:'1px solid var(--border-subtle)',display:'flex',flexDirection:'column',gap:12}}>
          <Checkbox label="Update my dish costs with these prices" defaultChecked description="Three dishes use eggs or cream."/>
          <div style={{display:'flex',gap:10,alignItems:'center',flexWrap:'wrap'}}>
            <Button onClick={()=>notify({tone:'good',icon:<Icon name="check" size={18}/>,title:'Invoice filed',message:'Three dish costs updated.',actionLabel:'See them'})}>File it</Button>
            <Button variant="secondary">Something looks wrong</Button>
          </div>
        </div>
      </Card>
    </div>
  </div>;
}
window.InvoicesScreen=InvoicesScreen;
})();