(function(){
if(!window.CostwiseDesignSystem_f2dfa3){if(!document.getElementById('cw-ds-missing')){const d=document.createElement('pre');d.id='cw-ds-missing';d.style.cssText='padding:24px;font:14px/1.6 monospace;color:#C0392B';d.textContent='Costwise design-system bundle not loaded \u2014 _ds_bundle.js is missing. It is generated by the compiler; reload once it exists.';document.body.appendChild(d);}return;}
const {Logo,Button,Input,Icon}=window.CostwiseDesignSystem_f2dfa3;
function LoginScreen({onSignIn}){
  React.useEffect(()=>{lucide.createIcons&&lucide.createIcons();},[]);
  return <div style={{display:'grid',gridTemplateColumns:'1.05fr 1fr',height:'100%',minHeight:0}}>
    <div style={{display:'flex',flexDirection:'column',justifyContent:'center',padding:'0 clamp(32px,7vw,96px)',gap:22}}>
      <Logo size={30} src="../../assets/logo-mark-transparent.png"/>
      <div>
        <h1 style={{font:'var(--type-display)',fontSize:'var(--text-3xl)',color:'var(--text-strong)'}}>Let's see where your money goes.</h1>
        <p style={{font:'var(--type-body)',color:'var(--text-muted)',marginTop:10,maxWidth:'42ch'}}>Costwise keeps an eye on what your dishes cost, so you can spend your evening in the kitchen instead of the spreadsheet.</p>
      </div>
      <form onSubmit={e=>{e.preventDefault();onSignIn();}} style={{display:'flex',flexDirection:'column',gap:14,maxWidth:380}}>
        <Input label="Email" type="email" defaultValue="marta@casaruiz.es" icon={<Icon name="mail" size={18}/>}/>
        <Input label="Password" type="password" defaultValue="············" icon={<Icon name="lock" size={18}/>}/>
        <Button size="lg" block type="submit" iconRight={<Icon name="arrow-right" size={18}/>}>Come on in</Button>
        <div style={{display:'flex',alignItems:'center',gap:10,color:'var(--text-faint)',font:'var(--type-caption)'}}><span style={{flex:1,height:1,background:'var(--border-subtle)'}}/>or<span style={{flex:1,height:1,background:'var(--border-subtle)'}}/></div>
        <Button variant="secondary" size="lg" block type="button" iconLeft={<Icon name="smartphone" size={18}/>}>Send me a code instead</Button>
        <p style={{font:'var(--type-caption)',color:'var(--text-muted)',textAlign:'center'}}>New here? <a href="#">Set up your place</a></p>
      </form>
    </div>
    <div style={{background:'var(--surface-brand-soft)',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:18,padding:40,borderLeft:'1px solid var(--border-subtle)'}}>
      <img src="../../assets/brand-illustration-cast-transparent.png" alt="" style={{width:'min(78%,440px)',height:'auto'}}/>
      <p style={{font:'var(--type-subheading)',color:'var(--green-800)',textAlign:'center',maxWidth:'26ch'}}>Food, money and a calculator walk into a kitchen.</p>
    </div>
  </div>;
}
window.LoginScreen=LoginScreen;
})();