(function(){
if(!window.CostwiseDesignSystem_f2dfa3){if(!document.getElementById('cw-ds-missing')){const d=document.createElement('pre');d.id='cw-ds-missing';d.style.cssText='padding:24px;font:14px/1.6 monospace;color:#C0392B';d.textContent='Costwise design-system bundle not loaded \u2014 _ds_bundle.js is missing. It is generated by the compiler; reload once it exists.';document.body.appendChild(d);}return;}
const {Card,StatTile,ProgressMeter,DataRow,Badge,Button,SuggestionChip,Composer,IconButton,Icon,Avatar,Tabs}=window.CostwiseDesignSystem_f2dfa3;
const {useState,useEffect}=React;
function TodayScreen({go,notify}){
  const [q,setQ]=useState('');
  const [range,setRange]=useState('week');
  useEffect(()=>{lucide.createIcons&&lucide.createIcons();},[range]);
  return <div style={{maxWidth:1000,margin:'0 auto',padding:'26px 26px 120px',display:'flex',flexDirection:'column',gap:'var(--gap-section)'}}>
    <section style={{display:'flex',flexDirection:'column',gap:16}}>
      <div style={{display:'flex',alignItems:'flex-end',gap:14,flexWrap:'wrap'}}>
        <div style={{flex:1,minWidth:280}}>
          <h1 style={{font:'var(--type-title)',color:'var(--text-strong)'}}>Morning, Marta.</h1>
          <p style={{font:'var(--type-body)',color:'var(--text-muted)',marginTop:6}}>Two things worth a look before service, and one bit of good news.</p>
        </div>
        <Tabs value={range} onChange={setRange} items={[{value:'week',label:'This week'},{value:'month',label:'Month'}]}/>
      </div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:'var(--gap-cards)'}}>
        <StatTile label="Food cost" value="31.4" unit="%" delta="↓ 2.1 pts" deltaTone="good" caption="target 30%"/>
        <StatTile label="Plate cost avg" value="€4.18" delta="↑ €0.22" deltaTone="over" caption="eggs, cream"/>
        <StatTile label="Waste" value="€184" delta="↓ €31" deltaTone="good" caption="best month yet"/>
        <StatTile variant="brand" label="Kept this month" value="€1,840"/>
      </div>
    </section>

    <section style={{display:'grid',gridTemplateColumns:'1.35fr 1fr',gap:'var(--gap-cards)',alignItems:'start'}}>
      <Card variant="accent" eyebrow="Costwise spotted this" title="Eggs are up 14% at Metro" action={<Badge tone="watch" dot>Worth a look</Badge>}>
        <p style={{font:'var(--type-body)',color:'var(--ink-800)'}}>That's 40c a plate on the carbonara. Two options: hold the price and take the hit for a fortnight, or go to €15.50 and stay at a 68% margin.</p>
        <div style={{display:'flex',gap:10,marginTop:16,flexWrap:'wrap'}}>
          <Button size="sm" onClick={()=>go('dishes')}>Look at the carbonara</Button>
          <Button size="sm" variant="secondary" onClick={()=>notify({title:'Parked until Monday',icon:<Icon name="clock" size={18}/>})}>Remind me Monday</Button>
        </div>
      </Card>
      <Card eyebrow="This week" title="Where the money went">
        <ProgressMeter thick segments={[{value:42},{value:24},{value:19},{value:15}]} max={100}/>
        <div style={{display:'flex',flexDirection:'column',gap:8,marginTop:14}}>
          {[['Produce','€1,240','--viz-1'],['Dairy & eggs','€712','--viz-2'],['Meat & fish','€560','--viz-3'],['Dry goods','€442','--viz-4']].map(([l,v,c])=>
            <div key={l} style={{display:'flex',alignItems:'center',gap:9,font:'var(--type-body)',fontSize:'var(--text-sm)'}}>
              <span style={{width:9,height:9,borderRadius:3,background:'var('+c+')'}}/>
              <span style={{flex:1,color:'var(--text-body)'}}>{l}</span>
              <span className="cw-money" style={{color:'var(--text-strong)'}}>{v}</span>
            </div>)}
        </div>
      </Card>
    </section>

    <section style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'var(--gap-cards)',alignItems:'start'}}>
      <Card padding="tight" eyebrow="Your dishes" title="Costs that moved" action={<IconButton size="sm" icon={<Icon name="chevron-right"/>} label="All dishes" onClick={()=>go('dishes')}/>}>
        <DataRow thumb={<Icon name="utensils"/>} title="Carbonara" subtitle="Plate cost €3.90 · menu €15.00" amount="26%" amountNote="food cost" end={<Badge tone="watch">Up 40c</Badge>} onClick={()=>go('dishes')}/>
        <DataRow thumb={<Icon name="salad"/>} title="Tomato & burrata" subtitle="Plate cost €4.35 · menu €13.50" amount="32%" amountNote="food cost" end={<Badge tone="over">Thin</Badge>} onClick={()=>go('dishes')}/>
        <DataRow thumb={<Icon name="fish"/>} title="Grilled sea bass" subtitle="Plate cost €6.10 · menu €22.00" amount="28%" amountNote="food cost" end={<Badge tone="good">Fine</Badge>} onClick={()=>go('dishes')}/>
      </Card>
      <Card padding="tight" eyebrow="Waiting on you" title="Two invoices to file" action={<Button size="sm" variant="ghost" onClick={()=>go('invoices')}>Open</Button>}>
        <DataRow thumb={<Icon name="receipt-text"/>} title="Metro · 18 Aug" subtitle="14 items · 3 prices changed" amount="€412.60" end={<Badge tone="watch">Check</Badge>} onClick={()=>go('invoices')}/>
        <DataRow thumb={<Icon name="receipt-text"/>} title="Local market · 17 Aug" subtitle="Photo, not read yet" amount="€96.20" end={<Badge tone="info">New</Badge>} onClick={()=>go('invoices')}/>
        <div style={{display:'flex',gap:8,paddingTop:12,flexWrap:'wrap'}}>
          <SuggestionChip icon={<Icon name="camera" size={15}/>} onClick={()=>notify({tone:'good',icon:<Icon name="check" size={18}/>,title:'Got it — reading the invoice',message:'I\u2019ll flag anything that went up.'})}>Snap a new one</SuggestionChip>
        </div>
      </Card>
    </section>

    <div style={{position:'sticky',bottom:0,paddingBottom:8,background:'linear-gradient(to top,var(--surface-page) 62%,rgba(253,251,246,0))',paddingTop:22}}>
      <div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:12}}>
        <SuggestionChip variant="accent" onClick={()=>notify({title:'Opening the carbonara',icon:<Icon name="sparkles" size={18}/>})}>Why did my margin drop?</SuggestionChip>
        <SuggestionChip>What should I push tonight?</SuggestionChip>
        <SuggestionChip>Cheapest dish on the menu</SuggestionChip>
      </div>
      <Composer value={q} onChange={e=>setQ(e.target.value)} onSend={()=>{setQ('');notify({tone:'good',title:'On it',message:'Costwise is looking at your last four weeks.'});}}
        lead={<Icon name="sparkles" size={16}/>} sendIcon={<Icon name="arrow-up" size={18}/>}
        tools={<><IconButton size="sm" round icon={<Icon name="camera" size={18}/>} label="Snap an invoice"/><IconButton size="sm" round icon={<Icon name="mic" size={18}/>} label="Speak"/></>}/>
    </div>
  </div>;
}
window.TodayScreen=TodayScreen;
})();