/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number;
                    order?: "asc" | "desc";
                    sort?: string;
                    itemsPerPage?: number;
                    offset?: number | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            recipes: {
                                /** Format: uuid */
                                id: string;
                                title: string;
                                totalCost: number;
                                createdBy: string;
                                dateCreated: string | null;
                                category: "starter" | "main" | "dessert";
                                tax: number;
                                /** Format: uri */
                                imgPath: string;
                                sellingPrice?: number;
                                profitMargin?: number;
                                foodCost: number;
                                userId: string;
                            }[];
                            count: {
                                count: number;
                            };
                        };
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        recipe: {
                            /** Format: uuid */
                            id: string;
                            title: string;
                            totalCost: number;
                            createdBy: string;
                            dateCreated: string | null;
                            category: "starter" | "main" | "dessert";
                            tax: number;
                            /** Format: uri */
                            imgPath: string;
                            sellingPrice?: number;
                            profitMargin?: number;
                            foodCost: number;
                            userId: string;
                        };
                        addedIngredients: {
                            /** Format: uuid */
                            recipeId: string;
                            /** Format: uuid */
                            ingredientId: string;
                            name: string;
                            iconBgColor?: string;
                            unit: string;
                            unitPrice: number;
                            quantity: number;
                        }[];
                        removedIngredients: {
                            /** Format: uuid */
                            recipeId: string;
                            /** Format: uuid */
                            ingredientId: string;
                            name: string;
                            iconBgColor?: string;
                            unit: string;
                            unitPrice: number;
                            quantity: number;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recipe detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            title: string;
                            totalCost: string;
                            createdBy: string;
                            dateCreated: string;
                            /** @enum {string} */
                            category: "starter" | "main" | "dessert";
                            tax: string;
                            imgPath: string;
                            sellingPrice: string;
                            profitMargin: string;
                            foodCost: string;
                            userId: string;
                            recipeIngredients: {
                                id: number;
                                recipeId: string;
                                ingredientId: string;
                                quantity: string;
                                ingredients: {
                                    id: string;
                                    name: string;
                                    unit: string;
                                    unitPrice: string;
                                    quantity: string;
                                    icon: string | null;
                                    usage: string;
                                };
                            }[];
                        };
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                        };
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        recipe: {
                            /** Format: uuid */
                            id: string;
                            title: string;
                            totalCost: number;
                            createdBy: string;
                            dateCreated: string | null;
                            category: "starter" | "main" | "dessert";
                            tax: number;
                            /** Format: uri */
                            imgPath: string;
                            sellingPrice?: number;
                            profitMargin?: number;
                            foodCost: number;
                            userId: string;
                        };
                        addedIngredients: {
                            /** Format: uuid */
                            recipeId: string;
                            /** Format: uuid */
                            ingredientId: string;
                            name: string;
                            iconBgColor?: string;
                            unit: string;
                            unitPrice: number;
                            quantity: number;
                        }[];
                        removedIngredients: {
                            /** Format: uuid */
                            recipeId: string;
                            /** Format: uuid */
                            ingredientId: string;
                            name: string;
                            iconBgColor?: string;
                            unit: string;
                            unitPrice: number;
                            quantity: number;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number;
                    order?: "asc" | "desc";
                    sort?: string;
                    itemsPerPage?: number;
                    offset?: number | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ingredients: {
                                /** Format: uuid */
                                id: string;
                                icon?: string | null;
                                name: string;
                                unit: "g" | "ml" | "kg" | "L" | "piece" | "";
                                unitPrice: number;
                                quantity: number;
                                usage: string;
                                userId: string;
                                category: "5dee106a-5050-443e-8368-03397e02af6d" | "a7b9013d-8f0d-4ef5-96fa-1f91df6e7fb5" | "1670a6d4-f212-4770-80c7-0e31c0f4c26b" | "80662af1-1943-4168-8549-ef721b0e9f54" | "b660f354-a89d-420c-80d1-ba0f16b433ec" | "90aae231-631c-4fed-baf0-929be5a26b13" | "25f19080-3387-4470-95df-598817d5ccfe" | "83602573-0b31-439c-8890-ee084a547c22" | "ad6fbf47-f289-4ffb-b070-a5957330a56b" | "f50e6aea-bb2d-42a1-8778-52cdbfec1540" | "0d4584b2-8bfa-4a82-9f11-a3b88af2d6c5" | "ef45178d-e566-4637-b7f9-abcf6d575466";
                                categoryName: "Produce" | "Meat & Poultry" | "Fish & Seafood" | "Dairy & Alternatives" | "Dry Goods" | "Spices & Seasonings" | "Oils, Vinegars, & Condiments" | "Frozen" | "Coffee & Tea" | "Beverages (Other)" | "Bakery" | "Other" | "";
                            }[];
                            count: {
                                count: number;
                            };
                        };
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        icon?: string | null;
                        name: string;
                        unit: "g" | "ml" | "kg" | "L" | "piece" | "";
                        unitPrice: number;
                        quantity: number;
                        usage: string;
                        userId: string;
                        suppliers: {
                            /** Format: uuid */
                            suppliersId: string;
                            unit: "g" | "ml" | "kg" | "L" | "piece" | "";
                            quantity: number | null;
                            price: number | null;
                            isActive: boolean;
                        }[];
                        category: "5dee106a-5050-443e-8368-03397e02af6d" | "a7b9013d-8f0d-4ef5-96fa-1f91df6e7fb5" | "1670a6d4-f212-4770-80c7-0e31c0f4c26b" | "80662af1-1943-4168-8549-ef721b0e9f54" | "b660f354-a89d-420c-80d1-ba0f16b433ec" | "90aae231-631c-4fed-baf0-929be5a26b13" | "25f19080-3387-4470-95df-598817d5ccfe" | "83602573-0b31-439c-8890-ee084a547c22" | "ad6fbf47-f289-4ffb-b070-a5957330a56b" | "f50e6aea-bb2d-42a1-8778-52cdbfec1540" | "0d4584b2-8bfa-4a82-9f11-a3b88af2d6c5" | "ef45178d-e566-4637-b7f9-abcf6d575466";
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ingredients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ingredient detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            icon?: string | null;
                            name: string;
                            unit: "g" | "ml" | "kg" | "L" | "piece" | "";
                            unitPrice: number;
                            quantity: number;
                            usage: string;
                            userId: string;
                            category: "5dee106a-5050-443e-8368-03397e02af6d" | "a7b9013d-8f0d-4ef5-96fa-1f91df6e7fb5" | "1670a6d4-f212-4770-80c7-0e31c0f4c26b" | "80662af1-1943-4168-8549-ef721b0e9f54" | "b660f354-a89d-420c-80d1-ba0f16b433ec" | "90aae231-631c-4fed-baf0-929be5a26b13" | "25f19080-3387-4470-95df-598817d5ccfe" | "83602573-0b31-439c-8890-ee084a547c22" | "ad6fbf47-f289-4ffb-b070-a5957330a56b" | "f50e6aea-bb2d-42a1-8778-52cdbfec1540" | "0d4584b2-8bfa-4a82-9f11-a3b88af2d6c5" | "ef45178d-e566-4637-b7f9-abcf6d575466";
                            categoryName: "Produce" | "Meat & Poultry" | "Fish & Seafood" | "Dairy & Alternatives" | "Dry Goods" | "Spices & Seasonings" | "Oils, Vinegars, & Condiments" | "Frozen" | "Coffee & Tea" | "Beverages (Other)" | "Bakery" | "Other" | "";
                        };
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                        };
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        icon?: string | null;
                        name: string;
                        unit: "g" | "ml" | "kg" | "L" | "piece" | "";
                        unitPrice: number;
                        quantity: number;
                        usage: string;
                        userId: string;
                        suppliers: {
                            /** Format: uuid */
                            suppliersId: string;
                            unit: "g" | "ml" | "kg" | "L" | "piece" | "";
                            quantity: number | null;
                            price: number | null;
                            isActive: boolean;
                        }[];
                        category: "5dee106a-5050-443e-8368-03397e02af6d" | "a7b9013d-8f0d-4ef5-96fa-1f91df6e7fb5" | "1670a6d4-f212-4770-80c7-0e31c0f4c26b" | "80662af1-1943-4168-8549-ef721b0e9f54" | "b660f354-a89d-420c-80d1-ba0f16b433ec" | "90aae231-631c-4fed-baf0-929be5a26b13" | "25f19080-3387-4470-95df-598817d5ccfe" | "83602573-0b31-439c-8890-ee084a547c22" | "ad6fbf47-f289-4ffb-b070-a5957330a56b" | "f50e6aea-bb2d-42a1-8778-52cdbfec1540" | "0d4584b2-8bfa-4a82-9f11-a3b88af2d6c5" | "ef45178d-e566-4637-b7f9-abcf6d575466";
                    };
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number;
                    order?: "asc" | "desc";
                    sort?: string;
                    itemsPerPage?: number;
                    offset?: number | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            suppliers: {
                                /** Format: uuid */
                                id: string;
                                userId: string;
                                name: string;
                                icon?: string | null;
                                category: ("5dee106a-5050-443e-8368-03397e02af6d" | "a7b9013d-8f0d-4ef5-96fa-1f91df6e7fb5" | "1670a6d4-f212-4770-80c7-0e31c0f4c26b" | "80662af1-1943-4168-8549-ef721b0e9f54" | "b660f354-a89d-420c-80d1-ba0f16b433ec" | "90aae231-631c-4fed-baf0-929be5a26b13" | "25f19080-3387-4470-95df-598817d5ccfe" | "83602573-0b31-439c-8890-ee084a547c22" | "ad6fbf47-f289-4ffb-b070-a5957330a56b" | "f50e6aea-bb2d-42a1-8778-52cdbfec1540" | "0d4584b2-8bfa-4a82-9f11-a3b88af2d6c5" | "ef45178d-e566-4637-b7f9-abcf6d575466")[];
                                contactPerson?: string | null;
                                /** Format: email */
                                email?: string | null;
                                phone?: string | null;
                                website?: string | null;
                                address?: {
                                    street?: string | null;
                                    city?: string | null;
                                    state?: string | null;
                                    postalCode?: string | null;
                                    country?: string | null;
                                };
                                financialData: {
                                    paymentTerms?: "" | "Net 30" | "Net 60" | "Net 90" | "Due on Receipt" | "COD" | "Prepaid" | null;
                                    vatNumber?: string | null;
                                };
                                notes?: string;
                                deliveryTime?: "" | "Same Day" | "1-2 Days" | "2-3 Days" | "Up to 5 days" | "Weekly" | "Same day" | "1-2 days" | "2-3 days" | null;
                                isActive: boolean;
                                dateAdded?: string | null;
                            }[];
                            count: {
                                count: number;
                            };
                        };
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        supplier: {
                            /** Format: uuid */
                            id: string;
                            userId: string;
                            name: string;
                            icon?: string | null;
                            category: ("5dee106a-5050-443e-8368-03397e02af6d" | "a7b9013d-8f0d-4ef5-96fa-1f91df6e7fb5" | "1670a6d4-f212-4770-80c7-0e31c0f4c26b" | "80662af1-1943-4168-8549-ef721b0e9f54" | "b660f354-a89d-420c-80d1-ba0f16b433ec" | "90aae231-631c-4fed-baf0-929be5a26b13" | "25f19080-3387-4470-95df-598817d5ccfe" | "83602573-0b31-439c-8890-ee084a547c22" | "ad6fbf47-f289-4ffb-b070-a5957330a56b" | "f50e6aea-bb2d-42a1-8778-52cdbfec1540" | "0d4584b2-8bfa-4a82-9f11-a3b88af2d6c5" | "ef45178d-e566-4637-b7f9-abcf6d575466")[];
                            contactPerson?: string | null;
                            /** Format: email */
                            email?: string | null;
                            phone?: string | null;
                            website?: string | null;
                            address?: {
                                street?: string | null;
                                city?: string | null;
                                state?: string | null;
                                postalCode?: string | null;
                                country?: string | null;
                            };
                            financialData: {
                                paymentTerms?: "" | "Net 30" | "Net 60" | "Net 90" | "Due on Receipt" | "COD" | "Prepaid" | null;
                                vatNumber?: string | null;
                            };
                            notes?: string;
                            deliveryTime?: "" | "Same Day" | "1-2 Days" | "2-3 Days" | "Up to 5 days" | "Weekly" | "Same day" | "1-2 days" | "2-3 days" | null;
                            isActive: boolean;
                            dateAdded?: string | null;
                        };
                        addedCategories: ("5dee106a-5050-443e-8368-03397e02af6d" | "a7b9013d-8f0d-4ef5-96fa-1f91df6e7fb5" | "1670a6d4-f212-4770-80c7-0e31c0f4c26b" | "80662af1-1943-4168-8549-ef721b0e9f54" | "b660f354-a89d-420c-80d1-ba0f16b433ec" | "90aae231-631c-4fed-baf0-929be5a26b13" | "25f19080-3387-4470-95df-598817d5ccfe" | "83602573-0b31-439c-8890-ee084a547c22" | "ad6fbf47-f289-4ffb-b070-a5957330a56b" | "f50e6aea-bb2d-42a1-8778-52cdbfec1540" | "0d4584b2-8bfa-4a82-9f11-a3b88af2d6c5" | "ef45178d-e566-4637-b7f9-abcf6d575466")[];
                        removedCategories: ("5dee106a-5050-443e-8368-03397e02af6d" | "a7b9013d-8f0d-4ef5-96fa-1f91df6e7fb5" | "1670a6d4-f212-4770-80c7-0e31c0f4c26b" | "80662af1-1943-4168-8549-ef721b0e9f54" | "b660f354-a89d-420c-80d1-ba0f16b433ec" | "90aae231-631c-4fed-baf0-929be5a26b13" | "25f19080-3387-4470-95df-598817d5ccfe" | "83602573-0b31-439c-8890-ee084a547c22" | "ad6fbf47-f289-4ffb-b070-a5957330a56b" | "f50e6aea-bb2d-42a1-8778-52cdbfec1540" | "0d4584b2-8bfa-4a82-9f11-a3b88af2d6c5" | "ef45178d-e566-4637-b7f9-abcf6d575466")[];
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/suppliers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Supplier detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            userId: string;
                            name: string;
                            icon?: string | null;
                            category: ("5dee106a-5050-443e-8368-03397e02af6d" | "a7b9013d-8f0d-4ef5-96fa-1f91df6e7fb5" | "1670a6d4-f212-4770-80c7-0e31c0f4c26b" | "80662af1-1943-4168-8549-ef721b0e9f54" | "b660f354-a89d-420c-80d1-ba0f16b433ec" | "90aae231-631c-4fed-baf0-929be5a26b13" | "25f19080-3387-4470-95df-598817d5ccfe" | "83602573-0b31-439c-8890-ee084a547c22" | "ad6fbf47-f289-4ffb-b070-a5957330a56b" | "f50e6aea-bb2d-42a1-8778-52cdbfec1540" | "0d4584b2-8bfa-4a82-9f11-a3b88af2d6c5" | "ef45178d-e566-4637-b7f9-abcf6d575466")[];
                            contactPerson?: string | null;
                            /** Format: email */
                            email?: string | null;
                            phone?: string | null;
                            website?: string | null;
                            address?: {
                                street?: string | null;
                                city?: string | null;
                                state?: string | null;
                                postalCode?: string | null;
                                country?: string | null;
                            };
                            financialData: {
                                paymentTerms?: "" | "Net 30" | "Net 60" | "Net 90" | "Due on Receipt" | "COD" | "Prepaid" | null;
                                vatNumber?: string | null;
                            };
                            notes?: string;
                            deliveryTime?: "" | "Same Day" | "1-2 Days" | "2-3 Days" | "Up to 5 days" | "Weekly" | "Same day" | "1-2 days" | "2-3 days" | null;
                            isActive: boolean;
                            dateAdded?: string | null;
                        };
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                        };
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        supplier: {
                            /** Format: uuid */
                            id: string;
                            userId: string;
                            name: string;
                            icon?: string | null;
                            category: ("5dee106a-5050-443e-8368-03397e02af6d" | "a7b9013d-8f0d-4ef5-96fa-1f91df6e7fb5" | "1670a6d4-f212-4770-80c7-0e31c0f4c26b" | "80662af1-1943-4168-8549-ef721b0e9f54" | "b660f354-a89d-420c-80d1-ba0f16b433ec" | "90aae231-631c-4fed-baf0-929be5a26b13" | "25f19080-3387-4470-95df-598817d5ccfe" | "83602573-0b31-439c-8890-ee084a547c22" | "ad6fbf47-f289-4ffb-b070-a5957330a56b" | "f50e6aea-bb2d-42a1-8778-52cdbfec1540" | "0d4584b2-8bfa-4a82-9f11-a3b88af2d6c5" | "ef45178d-e566-4637-b7f9-abcf6d575466")[];
                            contactPerson?: string | null;
                            /** Format: email */
                            email?: string | null;
                            phone?: string | null;
                            website?: string | null;
                            address?: {
                                street?: string | null;
                                city?: string | null;
                                state?: string | null;
                                postalCode?: string | null;
                                country?: string | null;
                            };
                            financialData: {
                                paymentTerms?: "" | "Net 30" | "Net 60" | "Net 90" | "Due on Receipt" | "COD" | "Prepaid" | null;
                                vatNumber?: string | null;
                            };
                            notes?: string;
                            deliveryTime?: "" | "Same Day" | "1-2 Days" | "2-3 Days" | "Up to 5 days" | "Weekly" | "Same day" | "1-2 days" | "2-3 days" | null;
                            isActive: boolean;
                            dateAdded?: string | null;
                        };
                        addedCategories: ("5dee106a-5050-443e-8368-03397e02af6d" | "a7b9013d-8f0d-4ef5-96fa-1f91df6e7fb5" | "1670a6d4-f212-4770-80c7-0e31c0f4c26b" | "80662af1-1943-4168-8549-ef721b0e9f54" | "b660f354-a89d-420c-80d1-ba0f16b433ec" | "90aae231-631c-4fed-baf0-929be5a26b13" | "25f19080-3387-4470-95df-598817d5ccfe" | "83602573-0b31-439c-8890-ee084a547c22" | "ad6fbf47-f289-4ffb-b070-a5957330a56b" | "f50e6aea-bb2d-42a1-8778-52cdbfec1540" | "0d4584b2-8bfa-4a82-9f11-a3b88af2d6c5" | "ef45178d-e566-4637-b7f9-abcf6d575466")[];
                        removedCategories: ("5dee106a-5050-443e-8368-03397e02af6d" | "a7b9013d-8f0d-4ef5-96fa-1f91df6e7fb5" | "1670a6d4-f212-4770-80c7-0e31c0f4c26b" | "80662af1-1943-4168-8549-ef721b0e9f54" | "b660f354-a89d-420c-80d1-ba0f16b433ec" | "90aae231-631c-4fed-baf0-929be5a26b13" | "25f19080-3387-4470-95df-598817d5ccfe" | "83602573-0b31-439c-8890-ee084a547c22" | "ad6fbf47-f289-4ffb-b070-a5957330a56b" | "f50e6aea-bb2d-42a1-8778-52cdbfec1540" | "0d4584b2-8bfa-4a82-9f11-a3b88af2d6c5" | "ef45178d-e566-4637-b7f9-abcf6d575466")[];
                    };
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    q: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Search results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ingredients?: {
                                /** Format: uuid */
                                id: string;
                                icon?: string | null;
                                name: string;
                                unit: "g" | "ml" | "kg" | "L" | "piece" | "";
                                unitPrice: number;
                                quantity: number;
                                usage: string;
                                userId: string;
                                category: "5dee106a-5050-443e-8368-03397e02af6d" | "a7b9013d-8f0d-4ef5-96fa-1f91df6e7fb5" | "1670a6d4-f212-4770-80c7-0e31c0f4c26b" | "80662af1-1943-4168-8549-ef721b0e9f54" | "b660f354-a89d-420c-80d1-ba0f16b433ec" | "90aae231-631c-4fed-baf0-929be5a26b13" | "25f19080-3387-4470-95df-598817d5ccfe" | "83602573-0b31-439c-8890-ee084a547c22" | "ad6fbf47-f289-4ffb-b070-a5957330a56b" | "f50e6aea-bb2d-42a1-8778-52cdbfec1540" | "0d4584b2-8bfa-4a82-9f11-a3b88af2d6c5" | "ef45178d-e566-4637-b7f9-abcf6d575466";
                                categoryName: "Produce" | "Meat & Poultry" | "Fish & Seafood" | "Dairy & Alternatives" | "Dry Goods" | "Spices & Seasonings" | "Oils, Vinegars, & Condiments" | "Frozen" | "Coffee & Tea" | "Beverages (Other)" | "Bakery" | "Other" | "";
                            }[];
                            recipes?: {
                                /** Format: uuid */
                                id: string;
                                title: string;
                                totalCost: number;
                                createdBy: string;
                                dateCreated: string | null;
                                category: "starter" | "main" | "dessert";
                                tax: number;
                                /** Format: uri */
                                imgPath: string;
                                sellingPrice?: number;
                                profitMargin?: number;
                                foodCost: number;
                                userId: string;
                            }[];
                        };
                    };
                };
                /** @description Error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recipe analytics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            avgProfitMargin: string | null;
                            avgFoodCost: string | null;
                            totalRecipes: number;
                        };
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Category analytics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            category: "starter" | "main" | "dessert";
                            count: number;
                            avgFoodCost: string | null;
                        }[];
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/margins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Margin highlights */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            topPerformers: {
                                /** Format: uuid */
                                id: string;
                                title: string;
                                totalCost: number;
                                createdBy: string;
                                dateCreated: string | null;
                                category: "starter" | "main" | "dessert";
                                tax: number;
                                /** Format: uri */
                                imgPath: string;
                                sellingPrice?: number;
                                profitMargin?: number;
                                foodCost: number;
                                userId: string;
                            }[];
                            attentionNeeded: {
                                /** Format: uuid */
                                id: string;
                                title: string;
                                totalCost: number;
                                createdBy: string;
                                dateCreated: string | null;
                                category: "starter" | "main" | "dessert";
                                tax: number;
                                /** Format: uri */
                                imgPath: string;
                                sellingPrice?: number;
                                profitMargin?: number;
                                foodCost: number;
                                userId: string;
                            }[];
                        };
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ingredient analytics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            totalIngredients: number;
                        };
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/high-impact-ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description High-impact ingredients */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            name: string;
                            icon: string | null;
                            usage: number;
                            category: string;
                        }[];
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query: {
                    filename: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Uploaded blob details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            url: string;
                        };
                    };
                };
                /** @description Error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
                /** @description Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                fieldErrors?: {
                                    [key: string]: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
