import '@fontsource/jetbrains-mono/400.css'
import '@fontsource/jetbrains-mono/500.css'
import { Analytics } from "@vercel/analytics/next"
import type { Metadata } from "next";
import "../globals.css";


import Sidebar from "../components/layout/sideBar";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { redirect } from "next/navigation";
import { Poppins, Sora } from 'next/font/google'
import Header from "../components/layout/header";
import TabBar from "../components/layout/tabBar";
import MobileSearchBoard from "../components/shared/search/mobileSearch/mobileSearchBoard";
import { cn } from '@/app/utils/cn';

export const metadata: Metadata = {
  title: "Costwise",
  description: "Generated by create next app",
  icons: {
    icon: '/images/costwise_logo.png',
    apple: [
      { url: '/apple-icon.png', sizes: '180x180', type: 'image/png' },
    ],
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'CostWise',
  },
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600']
});

const sora = Sora({
  subsets: ['latin'],
  weight: ['400', '600', '700', '800'],
  variable: '--font-sora'
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  
  if(!session?.user) {
    redirect("/signin")
  }
  
  return (
    <html lang="en" className={cn(poppins.className, sora.variable)}>
      <body>
        <SessionProvider session={session}>
            <div className="flex h-screen bg-[rgb(246,246,246)]">
              <Sidebar />
              <div className="relative flex flex-col flex-1 w-full overflow-hidden">
                <MobileSearchBoard />
                <Header session={session} />
                <main className="flex-1 overflow-auto flex flex-col pb-24 md:pb-0">
                  {children}
                  <Analytics/>
                </main>
                <TabBar />
              </div>
              
            </div>
        </SessionProvider>
      </body>
    </html>
  );
}