import { Analytics } from "@vercel/analytics/next"
import type { Metadata } from "next";
import "../globals.css";
import HomeContextProvider from "../context/homeContext/homeContext";
import Chat from "../components/chatUI/chat";
import Sidebar from "../components/layout/sideBar";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { redirect } from "next/navigation";
import { Poppins } from 'next/font/google'
import Header from "../components/layout/header";

export const metadata: Metadata = {
  title: "Costwise",
  description: "Generated by create next app",
  icons: {
    icon: '/images/costwise_logo.png'
  }
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600']
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  
  if(!session?.user) {
    redirect("/signin")
  }
  
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <SessionProvider session={session}>
          <HomeContextProvider>
            <div className="flex h-screen bg-[rgb(246,246,246)]">
              <Sidebar />
              <div className="flex flex-col flex-1 w-full overflow-hidden">
                <Header session={session} />
                <main className="flex-1 overflow-auto flex flex-col">
                  {children}
                  <Analytics/>
                </main>
              </div>
            </div>
            <Chat />
          </HomeContextProvider>
        </SessionProvider>
      </body>
    </html>
  );
}